export type IncludedFlag = 'O' | 'X' | '-';

export interface NonCoveredFeeCategory {
  id: string;
  title: string;
  order: number;
  showHeader: boolean;
}

export interface NonCoveredFeeItem {
  id: string;
  categoryId: string;
  order: number;
  majorCategory: string;
  subCategory: string;
  code: string;
  name: string;
  classification: string;
  fee: string;
  materialIncluded: IncludedFlag;
  medicationIncluded: IncludedFlag;
  notes: string;
  updatedAt: string;
}

export const NON_COVERED_FEE_CATEGORIES: NonCoveredFeeCategory[] = [
  { id: 'room', title: '', order: 1, showHeader: false },
  { id: 'inspection', title: '검사료', order: 2, showHeader: true },
  { id: 'material', title: '치료재료대', order: 3, showHeader: true },
  { id: 'medicine', title: '약제비', order: 4, showHeader: true },
  { id: 'certificate', title: '제증명수수료', order: 5, showHeader: true },
  { id: 'etc', title: '기타', order: 6, showHeader: true },
];

export const NON_COVERED_FEE_ITEMS: NonCoveredFeeItem[] = [
  {
    id: 'room-001',
    categoryId: 'room',
    order: 1,
    majorCategory: '상급병실료차액',
    subCategory: '상급병실료차액',
    code: 'ABZ02',
    name: '1인실',
    classification: '-',
    fee: '20',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2020.03.17',
  },

  {
    id: 'inspection-001',
    categoryId: 'inspection',
    order: 1,
    majorCategory: '검사료',
    subCategory: '순환기기능검사',
    code: 'FZ868',
    name: '동맥경화도검사(맥파전달속도측정)',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-002',
    categoryId: 'inspection',
    order: 2,
    majorCategory: '검사료',
    subCategory: '신경학적검사',
    code: 'CZ251',
    name: '전정유발근전위검사',
    classification: '-',
    fee: '5',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2026.05.14',
  },
  {
    id: 'inspection-003',
    categoryId: 'inspection',
    order: 3,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB489',
    name: '혈관-사지혈관 도플러초음파-하지정맥류',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.03.21',
  },
  {
    id: 'inspection-004',
    categoryId: 'inspection',
    order: 4,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB487',
    name: '혈관-사지혈관 도플러초음파-상지',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.03.21',
  },
  {
    id: 'inspection-005',
    categoryId: 'inspection',
    order: 5,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB484',
    name: '혈관-사지혈관 도플러초음파-하지',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.03.21',
  },
  {
    id: 'inspection-006',
    categoryId: 'inspection',
    order: 6,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB485',
    name: '혈관-사지혈관 도플러초음파-상지 정맥',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.03.21',
  },
  {
    id: 'inspection-007',
    categoryId: 'inspection',
    order: 7,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB488',
    name: '혈관-사지혈관 도플러초음파-하지 정맥',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.03.21',
  },
  {
    id: 'inspection-008',
    categoryId: 'inspection',
    order: 8,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB454',
    name: '복부-남성생식기 초음파',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.06.06',
  },
  {
    id: 'inspection-009',
    categoryId: 'inspection',
    order: 9,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EB451',
    name: '복부-여성생식기 초음파',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-010',
    categoryId: 'inspection',
    order: 10,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'ED432',
    name: '심장 초음파 검사',
    classification: '-',
    fee: '15',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2024.04.11',
  },
  {
    id: 'inspection-011',
    categoryId: 'inspection',
    order: 11,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'FM141',
    name: '갑상선·부갑상선 초음파',
    classification: '-',
    fee: '5',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2021.12.20',
  },
  {
    id: 'inspection-012',
    categoryId: 'inspection',
    order: 12,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'ED421',
    name: '경부 초음파',
    classification: '-',
    fee: '10',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2021.12.20',
  },
  {
    id: 'inspection-013',
    categoryId: 'inspection',
    order: 13,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'FM411',
    name: '근·골격계 초음파',
    classification: '-',
    fee: '10',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-014',
    categoryId: 'inspection',
    order: 14,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'ED482',
    name: '혈관초음파-경동맥',
    classification: '-',
    fee: '7',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '검사 범위에 따라 달라질 수 있음',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-015',
    categoryId: 'inspection',
    order: 15,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'FH661',
    name: '유도초음파(Ⅰ)',
    classification: '-',
    fee: '5',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-016',
    categoryId: 'inspection',
    order: 16,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'ED401',
    name: '단순초음파(Ⅰ)',
    classification: '-',
    fee: '3',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2026.03.12',
  },
  {
    id: 'inspection-017',
    categoryId: 'inspection',
    order: 17,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'FP002',
    name: '난소·골반 초음파',
    classification: '-',
    fee: '20',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '부위 및 검사 범위에 따라 달라질 수 있음',
    updatedAt: '2020.04.17',
  },
  {
    id: 'inspection-018',
    categoryId: 'inspection',
    order: 18,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'EZ904',
    name: '혈관 내 초음파',
    classification: '-',
    fee: '30',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2025.10.13',
  },
  {
    id: 'inspection-019',
    categoryId: 'inspection',
    order: 19,
    majorCategory: '초음파 검사료',
    subCategory: '초음파 검사료',
    code: 'FZ786',
    name: '수술 중 초음파',
    classification: '-',
    fee: '50~400',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2020.03.17',
  },
  {
    id: 'inspection-020',
    categoryId: 'inspection',
    order: 20,
    majorCategory: '처치 및 수술료 등',
    subCategory: '순환기',
    code: 'OZ304',
    name: '레이저정맥폐쇄술(대복재·소복재)',
    classification: '-',
    fee: '200~700',
    materialIncluded: 'O',
    medicationIncluded: 'O',
    notes: '',
    updatedAt: '2025.11.01',
  },
  {
    id: 'inspection-021',
    categoryId: 'inspection',
    order: 21,
    majorCategory: '처치 및 수술료 등',
    subCategory: '순환기',
    code: 'OZ305',
    name: '초음파 유도하 혈관경화요법',
    classification: '-',
    fee: '25',
    materialIncluded: 'O',
    medicationIncluded: 'O',
    notes: '',
    updatedAt: '2023.06.08',
  },
  {
    id: 'inspection-022',
    categoryId: 'inspection',
    order: 22,
    majorCategory: '처치 및 수술료 등',
    subCategory: '순환기',
    code: 'OZ303',
    name: '시아노아크릴레이트를 이용한 복재정맥 폐쇄술',
    classification: '-',
    fee: '300~720',
    materialIncluded: 'X',
    medicationIncluded: 'X',
    notes: '',
    updatedAt: '2026.03.30',
  },

  {
    id: 'material-001',
    categoryId: 'material',
    order: 1,
    majorCategory: '말초 내 영상 카테터',
    subCategory: '-',
    code: 'D.45042M',
    name: 'OPTICROSS 18 PERIPHERAL IMAGING CATHETER',
    classification: '-',
    fee: '150',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2026.03.05',
  },
  {
    id: 'material-002',
    categoryId: 'material',
    order: 2,
    majorCategory: '필터주입침(주사기)',
    subCategory: '-',
    code: 'M1102243',
    name: 'MICRO FILTER NEEDLE WITH SYRINGE',
    classification: '-',
    fee: '0.15',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '비급여 치료재료',
    updatedAt: '2020.07.01',
  },
  {
    id: 'material-003',
    categoryId: 'material',
    order: 3,
    majorCategory: '미용보호재',
    subCategory: '-',
    code: 'BM5000TH',
    name: 'F-CGF HEALER',
    classification: '-',
    fee: '20',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2025.09.20',
  },
  {
    id: 'material-004',
    categoryId: 'material',
    order: 4,
    majorCategory: '압박고정용 치료재료',
    subCategory: '-',
    code: 'BK7000C4',
    name: 'SANESCO',
    classification: '-',
    fee: '1.5',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2019.12.01',
  },
  {
    id: 'material-005',
    categoryId: 'material',
    order: 5,
    majorCategory: '자착성 탄력붕대',
    subCategory: '-',
    code: 'BK7100SJ',
    name: 'SAFE CO-BAND',
    classification: '-',
    fee: '7',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2026.09.01',
  },
  {
    id: 'material-006',
    categoryId: 'material',
    order: 6,
    majorCategory: '자착성 압박붕대',
    subCategory: '-',
    code: 'BK7337JP',
    name: 'NMB SUPPORT',
    classification: '-',
    fee: '8',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2026.10.13',
  },
  {
    id: 'material-007',
    categoryId: 'material',
    order: 7,
    majorCategory: '자착성 압박붕대',
    subCategory: '-',
    code: 'BK7301K',
    name: 'CEBIDCAL COHESIVE',
    classification: '-',
    fee: '2',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2026.03.30',
  },
  {
    id: 'material-008',
    categoryId: 'material',
    order: 8,
    majorCategory: '벡터고정재료',
    subCategory: '-',
    code: 'BK7117JF',
    name: 'FEMRO SUPPORT',
    classification: '-',
    fee: '3',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2021.07.01',
  },
  {
    id: 'material-009',
    categoryId: 'material',
    order: 9,
    majorCategory: '드레싱재료류',
    subCategory: '-',
    code: 'BM5112CD',
    name: 'FLEXIFIX',
    classification: '-',
    fee: '0.02',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2024.05.28',
  },
  {
    id: 'material-010',
    categoryId: 'material',
    order: 10,
    majorCategory: '드레싱고정류',
    subCategory: '-',
    code: 'BM5105SS',
    name: 'SSFIX',
    classification: '-',
    fee: '1.5',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2020.06.01',
  },
  {
    id: 'material-011',
    categoryId: 'material',
    order: 11,
    majorCategory: '시아노아크릴레이트 이용한 정맥폐쇄용 치료재료',
    subCategory: '-',
    code: 'EJ4320AA',
    name: 'NUVENA',
    classification: '-',
    fee: '80',
    materialIncluded: '-',
    medicationIncluded: '-',
    notes: '',
    updatedAt: '2026.03.30',
  },

  {
    id: 'medicine-001', categoryId: 'medicine', order: 1, majorCategory: '-', subCategory: '-', code: '659900681', name: '헤르페진엑스', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'medicine-002', categoryId: 'medicine', order: 2, majorCategory: '-', subCategory: '-', code: '645700110', name: '뉴리덱스주', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'medicine-003', categoryId: 'medicine', order: 3, majorCategory: '-', subCategory: '-', code: '641601400', name: '비카셀', classification: '-', fee: '0.075', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2019.07.01',
  },
  {
    id: 'medicine-004', categoryId: 'medicine', order: 4, majorCategory: '-', subCategory: '-', code: '652001030', name: '플라센스주사액 5mg', classification: '-', fee: '0.0245', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2019.06.01',
  },
  {
    id: 'medicine-005', categoryId: 'medicine', order: 5, majorCategory: '-', subCategory: '-', code: '670601051', name: '알파주사Ⅰ', classification: '-', fee: '7', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-006', categoryId: 'medicine', order: 6, majorCategory: '-', subCategory: '-', code: '670401511', name: '영양주사Ⅱ', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-007', categoryId: 'medicine', order: 7, majorCategory: '-', subCategory: '-', code: '650900201', name: '케어리커버리주', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-008', categoryId: 'medicine', order: 8, majorCategory: '-', subCategory: '-', code: '670607021', name: '영양주사Ⅲ', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-009', categoryId: 'medicine', order: 9, majorCategory: '-', subCategory: '-', code: '670607081', name: '혈액순환주사', classification: '-', fee: '7', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-010', categoryId: 'medicine', order: 10, majorCategory: '-', subCategory: '-', code: '645104241', name: '영양주사Ⅳ', classification: '-', fee: '9', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2024.07.24',
  },
  {
    id: 'medicine-011', categoryId: 'medicine', order: 11, majorCategory: '-', subCategory: '-', code: '682700070', name: '메조주사', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.09.06',
  },
  {
    id: 'medicine-012', categoryId: 'medicine', order: 12, majorCategory: '-', subCategory: '-', code: '681100201', name: '세파라민주', classification: '-', fee: '3', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2025.06.29',
  },
  {
    id: 'medicine-013', categoryId: 'medicine', order: 13, majorCategory: '-', subCategory: '-', code: '649500681', name: '엑소좀리드플러스주', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2025.10.17',
  },
  {
    id: 'medicine-014', categoryId: 'medicine', order: 14, majorCategory: '-', subCategory: '-', code: '641604651', name: '아미노프레쉬인퓨전', classification: '-', fee: '2.5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.01.09',
  },
  {
    id: 'medicine-015', categoryId: 'medicine', order: 15, majorCategory: '-', subCategory: '-', code: '684500021', name: '피아노페린주', classification: '-', fee: '30', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.03.12',
  },
  {
    id: 'medicine-016', categoryId: 'medicine', order: 16, majorCategory: '-', subCategory: '-', code: '654803980', name: '유로메스틱스액', classification: '-', fee: '60', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2020.04.17',
  },
  {
    id: 'medicine-017', categoryId: 'medicine', order: 17, majorCategory: '-', subCategory: '-', code: '646600511', name: '플라센리버 5mL', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2020.07.01',
  },
  {
    id: 'medicine-018', categoryId: 'medicine', order: 18, majorCategory: '-', subCategory: '-', code: '681120081', name: '세라젠에이주', classification: '-', fee: '1.5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.05.28',
  },
  {
    id: 'medicine-019', categoryId: 'medicine', order: 19, majorCategory: '-', subCategory: '-', code: '672900380', name: '셀리뉴비플러스 10mL', classification: '-', fee: '1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.05.28',
  },

  {
    id: 'certificate-001', categoryId: 'certificate', order: 1, majorCategory: '-', subCategory: '-', code: 'PDZ010001', name: '일반진단서', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2019.07.01',
  },
  {
    id: 'certificate-002', categoryId: 'certificate', order: 2, majorCategory: '-', subCategory: '-', code: 'PDZ010002', name: '근로능력평가용진단서', classification: '-', fee: '1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-003', categoryId: 'certificate', order: 3, majorCategory: '-', subCategory: '-', code: 'PDZ080000', name: '병무용진단서', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2021.06.01',
  },
  {
    id: 'certificate-004', categoryId: 'certificate', order: 4, majorCategory: '-', subCategory: '-', code: 'PDZ020001', name: '상해진단서', classification: '-', fee: '0.3', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-005', categoryId: 'certificate', order: 5, majorCategory: '-', subCategory: '-', code: 'PDZ090002', name: '입퇴원확인서', classification: '-', fee: '0.3', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-006', categoryId: 'certificate', order: 6, majorCategory: '-', subCategory: '-', code: 'PDZ090002-1', name: '수술확인서(세부 분류 기재)', classification: '-', fee: '1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.03.12',
  },
  {
    id: 'certificate-007', categoryId: 'certificate', order: 7, majorCategory: '-', subCategory: '-', code: 'PDZ100000', name: '진료확인서', classification: '-', fee: '0.1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-008', categoryId: 'certificate', order: 8, majorCategory: '-', subCategory: '-', code: 'PDZ120001', name: '소견서(보험회사 제출용 등)', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2020.03.12',
  },
  {
    id: 'certificate-009', categoryId: 'certificate', order: 9, majorCategory: '-', subCategory: '-', code: 'PDE010001', name: '영문진단서', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-010', categoryId: 'certificate', order: 10, majorCategory: '-', subCategory: '-', code: 'PDZ110001', name: '진료기록사본(1~5매)', classification: '-', fee: '0.1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-011', categoryId: 'certificate', order: 11, majorCategory: '-', subCategory: '-', code: 'PDZ110002', name: '진료기록사본(6매 이상/1매당)', classification: '-', fee: '0.01', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2018.04.03',
  },
  {
    id: 'certificate-012', categoryId: 'certificate', order: 12, majorCategory: '-', subCategory: '-', code: 'PDZ110004', name: '진료기록영상(CD)', classification: '-', fee: '1', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2019.06.01',
  },
  {
    id: 'certificate-013', categoryId: 'certificate', order: 13, majorCategory: '-', subCategory: '-', code: 'PDZ110005', name: '진료기록영상(DVD)', classification: '-', fee: '2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2023.05.01',
  },
  {
    id: 'certificate-014', categoryId: 'certificate', order: 14, majorCategory: '-', subCategory: '-', code: 'PDZ110006', name: '진료/조영영상 USB', classification: '-', fee: '3', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.06.30',
  },
  {
    id: 'certificate-015', categoryId: 'certificate', order: 15, majorCategory: '-', subCategory: '-', code: 'PDZ160001', name: '제증명 추가사본(재발급 포함)', classification: '-', fee: '5', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2025.09.04',
  },
  {
    id: 'certificate-016', categoryId: 'certificate', order: 16, majorCategory: '-', subCategory: '-', code: 'PDZ140002', name: '상급병실 사용확인서(입원 확인)', classification: '-', fee: '10', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2025.09.04',
  },

  {
    id: 'etc-001', categoryId: 'etc', order: 1, majorCategory: '건강검진', subCategory: '-', code: '-', name: '공 검진', classification: '-', fee: '65', materialIncluded: '-', medicationIncluded: '-', notes: '검진 항목별 별도 안내', updatedAt: '2022.05.10',
  },
  {
    id: 'etc-002', categoryId: 'etc', order: 2, majorCategory: '검사검진', subCategory: '-', code: '-', name: '직 검진', classification: '-', fee: '80', materialIncluded: '-', medicationIncluded: '-', notes: '검진 항목별 별도 안내', updatedAt: '2022.05.10',
  },
  {
    id: 'etc-003', categoryId: 'etc', order: 3, majorCategory: '건강검진', subCategory: '-', code: '-', name: '정밀검진', classification: '-', fee: '120', materialIncluded: '-', medicationIncluded: '-', notes: '검진 항목별 별도 안내', updatedAt: '2022.05.10',
  },
  {
    id: 'etc-004', categoryId: 'etc', order: 4, majorCategory: '식대', subCategory: '-', code: '-', name: '보호자식', classification: '-', fee: '0.8', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.03.12',
  },
  {
    id: 'etc-005', categoryId: 'etc', order: 5, majorCategory: '식대', subCategory: '-', code: '-', name: '공기밥', classification: '-', fee: '0.2', materialIncluded: '-', medicationIncluded: '-', notes: '', updatedAt: '2026.06.01',
  },
];
