import './globals.css';
import type { Metadata } from 'next';
import { SpoqaHanSansNeo } from '@/_lib/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className={`${SpoqaHanSansNeo.className} antialiased`}>
        {children}
      </body>
    </html>
  );
}
