import type {
  InlineContentData,
  InlineContentField,
} from '@/_lib/inline-content-shared';

export type PublicPageCopyConfig = {
  label: string;
  defaults: InlineContentData;
  fields: readonly InlineContentField[];
};

export const PUBLIC_PAGE_COPY = {
  '/about/doctors': {
    label: '의료진 목록 페이지 고정 문구',
    defaults: {
      doctorsTab: '의료진',
      departmentsTab: '진료과',
      searchLabel: '의료진 검색',
      searchPlaceholder: '의료진 성명 및 전문분야로 검색해보세요.',
      specialtyLabel: '전문분야',
      emptySpecialtyText: '전문분야 준비 중',
      vascularLabel: '혈관외과',
      radiologyLabel: '영상의학과',
      anesthesiologyLabel: '마취통증의학과',
      detailLabel: '상세보기',
      reservationLabel: '예약하기',
      emptyText: '조건에 맞는 의료진이 없습니다.',
      matchingMobileImage: '/assets/doctors/section-matching-mobile.png',
      matchingDesktopImage: '/assets/doctors/section-matching-desktop.png',
      matchingAlt: '지금 나에게 필요한 청맥 의료진은 누구일까?',
      matchingHref: '/',
      messageMobileImage: '/assets/doctors/section-message-mobile.png',
      messageDesktopImage: '/assets/doctors/section-message-desktop.png',
      messageAlt: '환자의 아픔을 먼저 듣고, 가장 안전한 길을 제시하겠습니다.',
      messageHref: '/',
    },
    fields: [
      { key: 'doctorsTab', label: '탭 - 의료진', type: 'text' },
      { key: 'departmentsTab', label: '탭 - 진료과', type: 'text' },
      { key: 'searchLabel', label: '검색 영역 제목', type: 'text' },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'specialtyLabel', label: '전문분야 라벨', type: 'text' },
      { key: 'emptySpecialtyText', label: '전문분야 미등록 문구', type: 'text' },
      { key: 'vascularLabel', label: '혈관외과 탭', type: 'text' },
      { key: 'radiologyLabel', label: '영상의학과 탭', type: 'text' },
      { key: 'anesthesiologyLabel', label: '마취통증의학과 탭', type: 'text' },
      { key: 'detailLabel', label: '상세보기 버튼', type: 'text' },
      { key: 'reservationLabel', label: '예약하기 버튼', type: 'text' },
      { key: 'emptyText', label: '검색 결과 없음 문구', type: 'text' },
      { key: 'matchingMobileImage', label: '매칭 배너 모바일', type: 'image' },
      { key: 'matchingDesktopImage', label: '매칭 배너 데스크탑', type: 'image' },
      { key: 'matchingAlt', label: '매칭 배너 대체문구', type: 'text' },
      { key: 'matchingHref', label: '매칭 배너 링크', type: 'url' },
      { key: 'messageMobileImage', label: '메시지 배너 모바일', type: 'image' },
      { key: 'messageDesktopImage', label: '메시지 배너 데스크탑', type: 'image' },
      { key: 'messageAlt', label: '메시지 배너 대체문구', type: 'text' },
      { key: 'messageHref', label: '메시지 배너 링크', type: 'url' },
    ],
  },
  '/about/tour': {
    label: '병원 둘러보기 고정 문구',
    defaults: {
      floorTab: '층별안내',
      facilityTab: '시설안내',
      facilitySearchPlaceholder: '찾으려는 시설을 검색하세요.',
      facilityEmpty: '검색 조건에 맞는 시설이 없습니다.',
      moreLabel: '더보기',
      buildingImage: '/assets/images/hospital-tour/building.png',
    },
    fields: [
      { key: 'floorTab', label: '층별안내 탭', type: 'text' },
      { key: 'facilityTab', label: '시설안내 탭', type: 'text' },
      { key: 'facilitySearchPlaceholder', label: '시설 검색 안내문', type: 'text' },
      { key: 'facilityEmpty', label: '검색 결과 없음 문구', type: 'text' },
      { key: 'moreLabel', label: '더보기 버튼', type: 'text' },
      { key: 'buildingImage', label: '층별안내 건물 이미지', type: 'image' },
    ],
  },
  '/about/equipment': {
    label: '첨단의료장비 고정 문구',
    defaults: {
      categoryAll: '전체',
      categoryImaging: '영상진단',
      categoryFunctional: '기능생체검사',
      categoryProcedure: '시술·수술',
      categorySpecial: '특수치료',
      equipmentSuffix: '장비',
      detailLabel: '자세히보기',
      diseasesEyebrow: '진단 가능 질환',
      diseasesTitle: '어떤 질환을 알 수 있나요?',
      casesEyebrow: '실제 진단 사례',
      casesTitle: '검사 결과, 이렇게 확인해요',
      emptyText: '해당 분류의 장비가 없습니다.',
      dvtBeforeImage: '/assets/images/medical-equipment/ct-case-dvt-before.jpg',
      dvtAfterImage: '/assets/images/medical-equipment/ct-case-dvt-after.jpg',
    },
    fields: [
      { key: 'categoryAll', label: '분류 - 전체', type: 'text' },
      { key: 'categoryImaging', label: '분류 - 영상진단', type: 'text' },
      { key: 'categoryFunctional', label: '분류 - 기능생체검사', type: 'text' },
      { key: 'categoryProcedure', label: '분류 - 시술·수술', type: 'text' },
      { key: 'categorySpecial', label: '분류 - 특수치료', type: 'text' },
      { key: 'equipmentSuffix', label: '장비 메뉴 접미사', type: 'text' },
      { key: 'detailLabel', label: '자세히보기 버튼', type: 'text' },
      { key: 'diseasesEyebrow', label: '진단 질환 보조제목', type: 'text' },
      { key: 'diseasesTitle', label: '진단 질환 제목', type: 'text' },
      { key: 'casesEyebrow', label: '진단 사례 보조제목', type: 'text' },
      { key: 'casesTitle', label: '진단 사례 제목', type: 'text' },
      { key: 'emptyText', label: '빈 목록 문구', type: 'text' },
      { key: 'dvtBeforeImage', label: 'DVT 치료 전 이미지', type: 'image' },
      { key: 'dvtAfterImage', label: 'DVT 치료 후 이미지', type: 'image' },
    ],
  },
  '/education-research/society': {
    label: '학회활동 고정 문구',
    defaults: {
      eyebrow: 'SOCIETY ACTIVITIES',
      introTitle:
        '청맥병원 의료진은 대한혈관외과학회, 대한정맥학회, UIP 세계정맥학회 등을 비롯한\n국내외 주요 학회의 중심에서 활발히 활동하고 있습니다.',
      introDescription:
        '정기 학술대회 참여와 치료 지침서 집필, 학술상 수상을 통해 혈관의학 발전에 기여하고,\n세계 혈관의학의 최신 흐름을 진료에 반영하기 위해 노력합니다.',
      featuredLabel: '· 주요 발표 ·',
      featuredGhost: 'FEATURED',
      emptyText: '해당 연도의 학회활동 자료를 준비 중입니다.',
      featuredBackgroundImage: '/assets/images/society-activities/spring-conference-2026.png',
    },
    fields: [
      { key: 'eyebrow', label: '영문 보조제목', type: 'text' },
      { key: 'introTitle', label: '소개 제목', type: 'editor', rows: 4 },
      { key: 'introDescription', label: '소개 설명', type: 'editor', rows: 4 },
      { key: 'featuredLabel', label: '주요 발표 라벨', type: 'text' },
      { key: 'featuredGhost', label: '배경 영문 문구', type: 'text' },
      { key: 'emptyText', label: '자료 없음 문구', type: 'text' },
      { key: 'featuredBackgroundImage', label: '주요 발표 배경 이미지', type: 'image' },
    ],
  },
  '/education-research/exchange': {
    label: '학술교류 고정 문구',
    defaults: {
      eyebrow: 'ACADEMIC EXCHANGE',
      introTitle:
        '혈관 치료의 올바른 기준을 세우기 위해\n청맥병원은 끊임없이 연구하고 소통합니다.',
      introDescription:
        '국내외 의료진과 임상 경험과 치료 노하우를 공유하고,\n술기 연수와 교육 프로그램을 지속적으로 운영하며 혈관의학의 저변을 함께 넓혀가고 있습니다.',
      searchPlaceholder: '검색어를 입력하세요',
      emptyText: '검색 조건에 맞는 학술교류 게시물이 없습니다.',
    },
    fields: [
      { key: 'eyebrow', label: '영문 보조제목', type: 'text' },
      { key: 'introTitle', label: '소개 제목', type: 'editor', rows: 4 },
      { key: 'introDescription', label: '소개 설명', type: 'editor', rows: 4 },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'emptyText', label: '검색 결과 없음 문구', type: 'text' },
    ],
  },
  '/community/consultation': {
    label: '의학상담 고정 문구',
    defaults: {
      noticeTitle: '확인해 주세요',
      notice1:
        '① 본 상담은 진료를 돕기 위한 보조적인 수단이며, 의료진의 직접 진료에 대한 진료를 대신할 수 없습니다. 정확한 진단과 치료 계획은 반드시 병원 내원을 통해 확인하시기 바랍니다.',
      notice2:
        '② 현재 전문의가 진료와 병행해 직접 답변을 작성하므로, 답변 완료까지 일정 시간이 소요될 수 있습니다. 신속한 답변은 정확하고 깊이 있는 답변을 드리기 위함이니 너그러운 양해 부탁드립니다.',
      notice3:
        '③ 개인정보(성명, 연락처, 환자번호 등)가 포함된 문의나 민감한 상담 내용은 비공개 게시물로 작성해 주시기 바랍니다.',
      searchPlaceholder: '검색어를 입력하세요',
      writeLabel: '문의글 작성하기',
    },
    fields: [
      { key: 'noticeTitle', label: '안내박스 제목', type: 'text' },
      { key: 'notice1', label: '안내문 1', type: 'editor', rows: 4 },
      { key: 'notice2', label: '안내문 2', type: 'editor', rows: 4 },
      { key: 'notice3', label: '안내문 3', type: 'editor', rows: 4 },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'writeLabel', label: '작성 버튼 문구', type: 'text' },
    ],
  },
  '/community/customer-voice': {
    label: '고객의 소리 고정 문구',
    defaults: {
      testimonialHeading: '칭찬합니다',
      praiseTitle: '감사합니다·칭찬해요',
      praiseDescription: '따뜻한 경험이나 따뜻한 마음을 전해주세요',
      complaintTitle: '건의합니다·불만/고충',
      complaintDescription: '불편했던 점이나 개선 의견을 남겨주세요',
      writeLabel: '작성하기',
      receiveHeading: '고객의 소리 접수방법',
      onlineTitle: '온라인 접수',
      onlineDescription: '현재 페이지에서 작성 (24시간)',
      phoneTitle: '전화 접수',
      phoneDescription: '051-804-1119 (병원 운영시간 내)',
      visitTitle: '방문 접수',
      visitDescription: '1층 원무과 · 고객상담실 (병원 운영시간 내)',
      processHeading: '처리절차',
      step1: '고객 의견 접수',
      step2: '관련 부서 검토',
      step3: '결과 회신 및 개선 활동',
      testimonial1Title: '박용범 원장님',
      testimonial1Content:
        '수술 전부터 퇴원 후 관리까지 세심하게 설명해주셔서 불안했던 마음이 놓였습니다. 정말 감사하다는 마음을 전하고 싶습니다.',
      testimonial1Author: '한○○님',
      testimonial2Title: '병동 간호사분들 감사합니다',
      testimonial2Content:
        '입원 기간 내내 친절한 선생님들이 사소한 것까지 챙겨주셔서 편안히 회복했습니다.',
      testimonial2Author: '한○○님',
      testimonial3Title: '칭찬합니다',
      testimonial3Content:
        '입원 기간 내내 간호사 선생님들이 사소한 것까지 챙겨주셔서 편안히 회복했습니다.',
      testimonial3Author: '한○○님',
      testimonial4Title: '친절한 안내에 감사드립니다',
      testimonial4Content:
        '검사부터 진료까지 차분하게 안내해주셔서 처음 방문했지만 불편함 없이 진료를 받을 수 있었습니다.',
      testimonial4Author: '이○○님',
    },
    fields: [
      { key: 'testimonialHeading', label: '칭찬 영역 제목', type: 'text' },
      { key: 'testimonial1Title', label: '칭찬 1 제목', type: 'text' },
      { key: 'testimonial1Content', label: '칭찬 1 내용', type: 'editor', rows: 4 },
      { key: 'testimonial1Author', label: '칭찬 1 작성자', type: 'text' },
      { key: 'testimonial2Title', label: '칭찬 2 제목', type: 'text' },
      { key: 'testimonial2Content', label: '칭찬 2 내용', type: 'editor', rows: 4 },
      { key: 'testimonial2Author', label: '칭찬 2 작성자', type: 'text' },
      { key: 'testimonial3Title', label: '칭찬 3 제목', type: 'text' },
      { key: 'testimonial3Content', label: '칭찬 3 내용', type: 'editor', rows: 4 },
      { key: 'testimonial3Author', label: '칭찬 3 작성자', type: 'text' },
      { key: 'testimonial4Title', label: '칭찬 4 제목', type: 'text' },
      { key: 'testimonial4Content', label: '칭찬 4 내용', type: 'editor', rows: 4 },
      { key: 'testimonial4Author', label: '칭찬 4 작성자', type: 'text' },
      { key: 'praiseTitle', label: '칭찬 접수 제목', type: 'text' },
      { key: 'praiseDescription', label: '칭찬 접수 설명', type: 'text' },
      { key: 'complaintTitle', label: '건의 접수 제목', type: 'text' },
      { key: 'complaintDescription', label: '건의 접수 설명', type: 'text' },
      { key: 'writeLabel', label: '작성 버튼', type: 'text' },
      { key: 'receiveHeading', label: '접수방법 제목', type: 'text' },
      { key: 'onlineTitle', label: '온라인 접수 제목', type: 'text' },
      { key: 'onlineDescription', label: '온라인 접수 설명', type: 'text' },
      { key: 'phoneTitle', label: '전화 접수 제목', type: 'text' },
      { key: 'phoneDescription', label: '전화 접수 설명', type: 'text' },
      { key: 'visitTitle', label: '방문 접수 제목', type: 'text' },
      { key: 'visitDescription', label: '방문 접수 설명', type: 'text' },
      { key: 'processHeading', label: '처리절차 제목', type: 'text' },
      { key: 'step1', label: 'STEP 1 문구', type: 'text' },
      { key: 'step2', label: 'STEP 2 문구', type: 'text' },
      { key: 'step3', label: 'STEP 3 문구', type: 'text' },
    ],
  },
  '/community/notice': {
    label: '공지사항 고정 문구',
    defaults: {
      majorHeading: '휴진 및 주요 공지',
      holidayTitle: '• 추석연휴 •',
      holidaySchedule: '9월 24일(목) ~ 9월 26일(토)',
      mobileHolidayTitle: '추석 연휴',
      mobileHolidaySchedule: '9월 15일(토) ~ 9월 17일(월)',
      naverOpenTitle: '네이버예약 OPEN',
      naverServiceTitle: '네이버예약 서비스 OPEN',
      moveTitle: '서면 메디컬센터 확장 이전 안내',
      naverDetailImage: '/assets/images/notice/naver-detail.png',
      naverCardImage: '/assets/images/notice/naver-card.png',
      moveCardImage: '/assets/images/notice/move-card.png',
      doctorLeaveHeading: '의료진별 휴진',
      tabAll: '전체',
      tabNotice: '공지사항',
      tabHoliday: '휴진안내',
      searchPlaceholder: '검색어를 입력하세요',
      columnTitle: '제목',
      columnDate: '등록일',
    },
    fields: [
      { key: 'majorHeading', label: '주요 공지 제목', type: 'text' },
      { key: 'holidayTitle', label: '연휴 제목', type: 'text' },
      { key: 'holidaySchedule', label: '연휴 일정', type: 'text' },
      { key: 'mobileHolidayTitle', label: '모바일 휴진 카드 제목', type: 'text' },
      { key: 'mobileHolidaySchedule', label: '모바일 휴진 카드 일정', type: 'text' },
      { key: 'naverOpenTitle', label: '모바일 네이버예약 제목', type: 'text' },
      { key: 'naverServiceTitle', label: '네이버예약 서비스 카드 제목', type: 'text' },
      { key: 'moveTitle', label: '확장 이전 카드 제목', type: 'text' },
      { key: 'naverDetailImage', label: '모바일 네이버예약 이미지', type: 'image' },
      { key: 'naverCardImage', label: '네이버예약 카드 이미지', type: 'image' },
      { key: 'moveCardImage', label: '확장 이전 카드 이미지', type: 'image' },
      { key: 'doctorLeaveHeading', label: '의료진별 휴진 제목', type: 'text' },
      { key: 'tabAll', label: '전체 탭', type: 'text' },
      { key: 'tabNotice', label: '공지사항 탭', type: 'text' },
      { key: 'tabHoliday', label: '휴진안내 탭', type: 'text' },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'columnTitle', label: '목록 제목 열', type: 'text' },
      { key: 'columnDate', label: '목록 등록일 열', type: 'text' },
    ],
  },
  '/community/news': {
    label: '청맥뉴스 고정 문구',
    defaults: {
      tabAll: '전체',
      tabInside: '원내소식',
      tabPress: '언론보도',
      searchPlaceholder: '검색어를 입력하세요.',
      emptyText: '검색 조건에 맞는 청맥뉴스가 없습니다.',
    },
    fields: [
      { key: 'tabAll', label: '전체 탭', type: 'text' },
      { key: 'tabInside', label: '원내소식 탭', type: 'text' },
      { key: 'tabPress', label: '언론보도 탭', type: 'text' },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'emptyText', label: '검색 결과 없음 문구', type: 'text' },
    ],
  },
  '/guide/partner-hospital': {
    label: '의료협약병원 고정 문구',
    defaults: {
      overviewTitle: '협약기관 현황',
      overviewDescription:
        '청맥병원과 협약을 맺은 기관을 이용하시면 진료비 감면 등 폭넓은 의료·제휴 혜택을 누리실 수 있습니다.',
      handshakeImage: '/assets/images/partner-hospital/partnership-handshake.jpg',
      categoryAll: '전체',
      categoryCare: '진료협약',
      categorySupport: '제휴/지원',
      searchPlaceholder: '검색어를 입력하세요',
      emptyText: '검색 조건에 맞는 협약기관이 없습니다.',
      agreementLabel: '협약내용',
      phoneLabel: '전화번호',
    },
    fields: [
      { key: 'overviewTitle', label: '협약기관 현황 제목', type: 'text' },
      { key: 'overviewDescription', label: '협약기관 현황 설명', type: 'editor', rows: 4 },
      { key: 'handshakeImage', label: '모바일 악수 이미지', type: 'image' },
      { key: 'categoryAll', label: '분류 - 전체', type: 'text' },
      { key: 'categoryCare', label: '분류 - 진료협약', type: 'text' },
      { key: 'categorySupport', label: '분류 - 제휴/지원', type: 'text' },
      { key: 'searchPlaceholder', label: '검색창 안내문', type: 'text' },
      { key: 'emptyText', label: '검색 결과 없음 문구', type: 'text' },
      { key: 'agreementLabel', label: '협약내용 라벨', type: 'text' },
      { key: 'phoneLabel', label: '전화번호 라벨', type: 'text' },
    ],
  },
} satisfies Record<string, PublicPageCopyConfig>;

export type PublicPageCopyPath = keyof typeof PUBLIC_PAGE_COPY;

export function getPublicPageCopyConfig(path: PublicPageCopyPath) {
  return PUBLIC_PAGE_COPY[path];
}
